# Generated by Django 5.0.6 on 2026-08-17 12:17

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Уникальный код продукта в диапазоне 001..999', max_length=3, unique=True, verbose_name='Код')),
                ('name', models.CharField(max_length=200, verbose_name='Наименование')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
            ],
            options={
                'verbose_name': 'Продукт',
                'verbose_name_plural': 'Продукты',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='Название')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='Код')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
            ],
            options={
                'verbose_name': 'Цех',
                'verbose_name_plural': 'Цеха',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='Line',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveSmallIntegerField(verbose_name='Номер линии')),
                ('name', models.CharField(max_length=150, verbose_name='Название')),
                ('controller_id', models.CharField(blank=True, help_text='Значение поля controller_id, которое присылает контроллер', max_length=64, unique=True, verbose_name='Идентификатор контроллера ОВЕН')),
                ('is_active', models.BooleanField(default=True, verbose_name='Линия в эксплуатации')),
                ('last_seen', models.DateTimeField(blank=True, null=True, verbose_name='Последнее обращение контроллера')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создана')),
                ('current_product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lines_current', to='dashboard.product', verbose_name='Текущий продукт')),
            ],
            options={
                'verbose_name': 'Линия',
                'verbose_name_plural': 'Линии',
                'ordering': ['shop__code', 'number'],
            },
        ),
        migrations.CreateModel(
            name='ProductAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(verbose_name='Начало (момент смены ключа)')),
                ('ended_at', models.DateTimeField(blank=True, null=True, verbose_name='Окончание')),
                ('target_quantity', models.BigIntegerField(blank=True, null=True, verbose_name='План (шт.)')),
                ('total_count', models.BigIntegerField(default=0, verbose_name='Изготовлено (шт.)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='dashboard.line', verbose_name='Линия')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assignments', to='dashboard.product', verbose_name='Продукт')),
            ],
            options={
                'verbose_name': 'Задание (смена продукта)',
                'verbose_name_plural': 'Задания (смены продукта)',
                'ordering': ['-started_at'],
            },
        ),
        migrations.AddField(
            model_name='line',
            name='current_assignment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='dashboard.productassignment', verbose_name='Текущее задание'),
        ),
        migrations.CreateModel(
            name='ControllerReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.BigIntegerField(default=0, verbose_name='Суммарное показание счётчика')),
                ('delta', models.BigIntegerField(default=0, verbose_name='Приращение за приём')),
                ('received_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Время получения')),
                ('line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='readings', to='dashboard.line', verbose_name='Линия')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='readings', to='dashboard.product', verbose_name='Продукт')),
                ('assignment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='readings', to='dashboard.productassignment', verbose_name='Задание')),
            ],
            options={
                'verbose_name': 'Показание контроллера',
                'verbose_name_plural': 'Показания контроллеров',
                'ordering': ['-received_at'],
            },
        ),
        migrations.AddField(
            model_name='line',
            name='shop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='dashboard.shop', verbose_name='Цех'),
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('admin', 'Администратор'), ('operator', 'Оператор'), ('viewer', 'Наблюдатель')], default='viewer', max_length=20, verbose_name='Роль')),
                ('shop', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff', to='dashboard.shop', verbose_name='Цех (для оператора)')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Профиль пользователя',
                'verbose_name_plural': 'Профили пользователей',
            },
        ),
        migrations.CreateModel(
            name='ProductionRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('minute_start', models.DateTimeField(verbose_name='Начало минуты')),
                ('count', models.BigIntegerField(default=0, verbose_name='Количество (шт.)')),
                ('assignment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='records', to='dashboard.productassignment', verbose_name='Задание')),
                ('line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='dashboard.line', verbose_name='Линия')),
            ],
            options={
                'verbose_name': 'Минутный счёт',
                'verbose_name_plural': 'Минутные счета',
                'ordering': ['minute_start'],
                'indexes': [models.Index(fields=['line', 'minute_start'], name='dashboard_p_line_id_16971b_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='productionrecord',
            constraint=models.UniqueConstraint(fields=('line', 'minute_start'), name='uniq_line_minute'),
        ),
        migrations.AddConstraint(
            model_name='line',
            constraint=models.UniqueConstraint(fields=('shop', 'number'), name='uniq_line_shop_number'),
        ),
    ]
