# Generated by Django 5.0.6 on 2026-08-17 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='color',
            field=models.CharField(default='#1f6feb', help_text='HEX-цвет (например #1f6feb) для столбиков диаграммы', max_length=7, verbose_name='Цвет на диаграмме'),
        ),
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, help_text='Необязательное изображение, отображается на столбике диаграммы', null=True, upload_to='products/', verbose_name='Изображение'),
        ),
    ]
