# Generated by Django 5.0.6 on 2026-08-17 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_product_color_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='code_1c',
            field=models.CharField(blank=True, help_text='Код продукта в учётной системе 1С (заполняется администратором вручную)', max_length=64, verbose_name='Код 1С'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, help_text='Необязательное изображение продукта (продукт можно добавить без картинки)', null=True, upload_to='products/', verbose_name='Изображение'),
        ),
    ]
