# Generated by Django 5.0.6 on 2026-08-17 17:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_product_code_1c_alter_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='shop',
            field=models.ForeignKey(blank=True, help_text='Цех, которому принадлежит продукт (пусто — общий продукт)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='dashboard.shop', verbose_name='Цех'),
        ),
    ]
