# Generated by Django 5.0.6 on 2026-08-18 10:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_product_shop'),
    ]

    operations = [
        migrations.AddField(
            model_name='line',
            name='performance_per_hour',
            field=models.PositiveIntegerField(default=0, help_text='Нормативная производительность линии, шт. в час (заполняется администратором)', verbose_name='Производительность в час (шт.)'),
        ),
        migrations.CreateModel(
            name='Counter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название счетчика')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('line', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='counter', to='dashboard.line', verbose_name='Линия')),
            ],
            options={
                'verbose_name': 'Счетчик',
                'verbose_name_plural': 'Счетчики',
                'ordering': ['id'],
            },
        ),
    ]
