# Generated by Django 5.0.6 on 2026-08-18 (SystemConfig — настройка источника данных)

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_line_performance_per_hour_counter'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_source', models.CharField(choices=[('db', 'База данных (PostgreSQL)'), ('dbf', 'Файлы DBF')], default='db', max_length=10, verbose_name='Источник данных для отчётов')),
                ('dbf_dir', models.CharField(blank=True, help_text='Путь к папке, где лежат файлы *.dbf. Пусто — корневая папка проекта (где лежат 20442023.dbf и т.п.). Можно указать абсолютный путь (C:\\dbf) или относительный.', max_length=500, verbose_name='Папка с файлами DBF')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
            ],
            options={
                'verbose_name': 'Настройка системы',
                'verbose_name_plural': 'Настройки системы',
            },
        ),
    ]
