# Generated by Django 5.0.6 on 2026-08-18 (SystemConfig.logo — логотип в шапке)

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_systemconfig'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemconfig',
            name='logo',
            field=models.ImageField(blank=True, help_text='Изображение в шапке рядом с надписью «Молвест.Учет.Продукции» вместо иконки-коробки. Рекомендуется PNG с прозрачностью, высота ~30–40 px. Если не загружено — показывается иконка.', null=True, upload_to='logo/', verbose_name='Логотип (в шапке)'),
        ),
    ]
