# Generated by Django 5.0.6 on 2026-08-18 (SystemConfig.logo удалено — логотип вшит в проект)

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_systemconfig_logo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='systemconfig',
            name='logo',
        ),
    ]
