# Generated by Django 5.0.6 on 2026-08-18 (ReportLog — журнал формирований отчётов)

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_systemconfig_remove_logo'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tab', models.CharField(max_length=20, verbose_name='Вкладка')),
                ('rtype', models.CharField(max_length=30, verbose_name='Тип отчёта')),
                ('period_start', models.DateTimeField(verbose_name='Начало периода')),
                ('period_end', models.DateTimeField(verbose_name='Окончание периода')),
                ('number', models.PositiveIntegerField(verbose_name='Номер за период')),
                ('identifier', models.CharField(max_length=64, verbose_name='Идентификатор отчёта')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Сформирован')),
                ('line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_logs', to='dashboard.line', verbose_name='Линия')),
            ],
            options={
                'verbose_name': 'Формирование отчёта',
                'verbose_name_plural': 'Формирования отчётов',
                'ordering': ['-created_at'],
            },
        ),
    ]
