# Generated by Django 5.0.6 on 2026-08-19 (ReportLog.line стал необязательным — журнал работает и в режиме DBF)

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_reportlog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportlog',
            name='line',
            field=models.ForeignKey(blank=True, help_text='Пусто для запасного режима (файлы DBF).', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='report_logs', to='dashboard.line', verbose_name='Линия'),
        ),
    ]
