# Generated by Django 5.0.6 on 2026-08-23 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0010_reportlog_line_nullable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportlog',
            name='rtype',
            field=models.CharField(choices=[('total', 'Итоговый'), ('detail', 'Подробный'), ('detail_shifts', 'Подробный по сменам'), ('chart', 'График'), ('downtime', 'Простои'), ('by_shift', 'По смене'), ('total_days', 'Итоговый по дням'), ('gross', 'Валовый'), ('total_months', 'Итоговый по месяцам'), ('total_quarters', 'Итоговый по кварталам'), ('total_year', 'Итоговый в пределах года')], max_length=30, verbose_name='Тип отчёта'),
        ),
        migrations.AlterField(
            model_name='reportlog',
            name='tab',
            field=models.CharField(choices=[('shift', 'Смена'), ('day', 'Сутки'), ('month', 'Месяц'), ('quarter', 'Квартал'), ('year', 'Год'), ('period', 'Период')], max_length=20, verbose_name='Вкладка'),
        ),
    ]
