# Generated by Django 5.0.6 on 2026-08-25 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0011_alter_reportlog_rtype_alter_reportlog_tab'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='productionrecord',
            name='uniq_line_minute',
        ),
        migrations.AddField(
            model_name='systemconfig',
            name='switch_pin',
            field=models.CharField(default='2020', help_text='Пин-код, который оператор вводит при смене кода продукта на линии (только цифры). По умолчанию: 2020.', max_length=10, verbose_name='Пин-код смены продукта'),
        ),
        migrations.AddConstraint(
            model_name='productionrecord',
            constraint=models.UniqueConstraint(fields=('line', 'minute_start', 'assignment'), name='uniq_line_minute_assignment'),
        ),
    ]
