# Generated by Django 5.0.6 on 2026-09-04 12:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0012_remove_productionrecord_uniq_line_minute_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DbfCounterLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Код счётчика из имени файла DBF (например 2044 из 20442023.dbf).', max_length=20, unique=True, verbose_name='Код счётчика (DBF)')),
                ('line', models.ForeignKey(help_text='Линия, к которой относится этот код счётчика (её название будет подставляться в отчёты).', on_delete=django.db.models.deletion.CASCADE, related_name='dbf_counters', to='dashboard.line', verbose_name='Линия')),
            ],
            options={
                'verbose_name': 'Привязка счётчика DBF к линии',
                'verbose_name_plural': 'Привязки счётчиков DBF к линиям',
                'ordering': ['code'],
            },
        ),
    ]
